

POST http://localhost:3003/api/blogs/5a422b3a1b54a676234d17f9
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RfbmFtZSIsImlkIjoiNjNmODNjM2ZhNDhjYjFlM2Q2ZDI1OWVkIiwiaWF0IjoxNjc3MjEyNzM1fQ.rTXTGcfgiDyAXKUTYNV3Wg08Cxnv_ZhItaleA1jlFS8'

